spring:
  application:
    name: stock-market-analyzer
  datasource:
    url: jdbc:mysql://localhost:3306/demo?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
alpha:
  vantage:
    api:
      key: 59TW5REYQ45BQ46D